List<String> occ = [
  "Agriculture",
  "Architecture",
  "Biological and Biomedical Sciences",
  "Business",
  "Communications and Journalism",
  "Computer Sciences",
  "Culinary Arts and Personal Services",
  "Education",
  "Engineering",
  "Legal",
  "Liberal Arts and Humanities",
  "Mechanic and Repair Technologies",
  "Medical and Health Professions",
  "Other",
  "Physical Sciences",
  "Psychology",
  "Transportation and Distribution",
  "Visual and Performing Arts",
];
